

CREATE TABLE  G4_ROLLOUT 
   (	ROLLOUTID NUMBER NOT NULL ENABLE, 
	ROLLOUTNAME VARCHAR2(1000) NOT NULL ENABLE, 
	REDEMP_CENTER VARCHAR2(1000) NOT NULL ENABLE, 
	ROLLOUTDATE TIMESTAMP (6) DEFAULT systimestamp + interval '30' Minute, 
	BUNDLEID NUMBER NOT NULL ENABLE, 
	VCID NUMBER NOT NULL ENABLE, 
	STATEID NUMBER NOT NULL ENABLE, 
	LGAID NUMBER NOT NULL ENABLE, 
	ROLLOUTSTATUS VARCHAR2(20), 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	DEALERID NUMBER, 
	FIELDSTAFFID NUMBER, 
	FARMERS_CON NUMBER, 
	RES_TYPEID NUMBER, 
	USERNAME VARCHAR2(200), 
	 CONSTRAINT G4_ROLLOUTID_PK PRIMARY KEY (ROLLOUTID)
  USING INDEX  ENABLE, 
	 CONSTRAINT G4_ROLLOUT_RNAME_UK UNIQUE (ROLLOUTNAME)
  USING INDEX  ENABLE, 
	 CONSTRAINT G4_ROUT_RCENTER_UK UNIQUE (REDEMP_CENTER)
  USING INDEX  ENABLE
   );
   
   DROP SEQUENCE   G4_ROLLOUT_SEQ;
   
   CREATE SEQUENCE   G4_ROLLOUT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE;


CREATE OR REPLACE TRIGGER  G4_ROLLOUT_TRIG 
BEFORE INSERT ON g4_rollout
FOR EACH ROW
BEGIN
IF :new.rolloutid is null
THEN SELECT g4_rollout_seq.nextval
INTO :new.rolloutid
FROM DUAL;
END IF;
END;


CREATE SEQUENCE   G4_ROUT_CRITWMAP_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE


CREATE TABLE  G4_ROUT_WARDS_MAPPING 
   (	RWMID NUMBER, 
	ROLLOUTID NUMBER NOT NULL ENABLE, 
	BUNDLEID NUMBER NOT NULL ENABLE, 
	VCID NUMBER NOT NULL ENABLE, 
	STATEID NUMBER NOT NULL ENABLE, 
	LGAID NUMBER NOT NULL ENABLE, 
	WARDID NUMBER NOT NULL ENABLE, 
	DEALERID NUMBER NOT NULL ENABLE, 
	FIELDSTAFFID NUMBER NOT NULL ENABLE, 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	PROCESSEDID NUMBER, 
	 CONSTRAINT G4_RWMID_PK2 PRIMARY KEY (RWMID)
  USING INDEX  ENABLE, 
	 CONSTRAINT G4VCID_BID_WARD_UK UNIQUE (BUNDLEID, VCID, WARDID)
  USING INDEX  ENABLE
   );
   
   
   
   CREATE INDEX  G4_ROUT_R_B_V_S_L_W_D_F_P ON  G4_ROUT_WARDS_MAPPING (ROLLOUTID, BUNDLEID, VCID, STATEID, LGAID, WARDID, DEALERID, FIELDSTAFFID, PROCESSEDID)
