select * from t;

desc g4_value_chain;

drop SEQUENCE   "G4_VALUE_CHAIN_SEQ";

CREATE SEQUENCE   "G4_VALUE_CHAIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 ORDER  NOCYCLE
/


insert into G4_VALUE_CHAIN
select * from g3_value_chain;

commit;



SELECT 
   "G3_ROLLOUT"."ROLLOUTID" "ROLLOUTID", 
   "G3_ROLLOUT"."ROLLOUTNAME" "ROLLOUTNAME", 
   "G3_ROLLOUT"."REDEMP_CENTER" "REDEMP_CENTER", 
   "G3_ROLLOUT"."ROLLOUTDATE" "ROLLOUTDATE", 
   "G3_BUNDLES"."BUNDLENAME" "BUNDLENAME",
   "G3_ROLLOUT"."FARMERS_CON" "FARMERS_CON",
   "G3_VALUE_CHAIN"."VCNAME" "VCNAME", 
   "G3_STATES"."STATENAME" "STATENAME", 
   "G3_LGA"."LGANAME" "LGANAME",
   "G3_RESPONSE_TYPE"."RES_TYPENAME" "RES_TYPENAME",
    "G3_ROLLOUT"."ROLLOUTSTATUS" "ROLLOUTSTATUS", 
      "G3_AGRODEALERS"."DEALERNAME" "DEALERNAME", 
   "G3_FIELDSTAFF"."FIELDSTAFFNAME" "FIELDSTAFFNAME"
FROM  G3_ROLLOUT,G3_LGA,G3_STATES,G3_BUNDLES,G3_VALUE_CHAIN,G3_FIELDSTAFF,G3_AGRODEALERS,g3_response_type
WHERE G3_ROLLOUT.LGAID     =  G3_LGA.LGAID
AND   G3_ROLLOUT.STATEID   =  G3_STATES.STATEID
AND   G3_ROLLOUT.BUNDLEID  =  G3_BUNDLES.BUNDLEID
AND   G3_ROLLOUT.DEALERID  =  G3_AGRODEALERS.DEALERID
AND   G3_ROLLOUT.VCID      =  G3_VALUE_CHAIN.VCID
AND   G3_ROLLOUT.FIELDSTAFFID      =  G3_FIELDSTAFF.FIELDSTAFFID
AND   G3_ROLLOUT.RES_TYPEID =  g3_response_type.RES_TYPEID;