fmard21472AA2946


insert into kogitest(Id ,     
 title  ,  
 farmerID, 
 surname  ,
 firstname ,                
 middlename ,               
 gender     ,               
 dob        ,               
 educationlevel,            
 phoneNumber ,              
 state      ,               
 LGA         ,              
 village      ,             
 farmersaddress,            
 height         ,           
 fatherssurname  ,          
 fathersfirstname ,         
 motherssurname    ,        
 mothersfirstname   ,       
 maritalstatus       ,      
 employmentstatus    ,      
 preferredlanguage   ,      
 surnamenextofkin    ,      
 firstnamenextofkin  ,      
 relationshipwithnextofkin, 
 townnextofkin            , 
 addressnextofkin          ,
 statenextofkin            ,
 lganextofkin              ,
 enumstate,
 enumlga   ,               
 enumvillage,              
 enumward    ,             
 farmerscrop  ,            
 farmsize      ,           
 farmlocation   ,          
 agricservices   ,         
 farmerslivestock ,        
 farmersfisheries  ,       
 groupname          ,      
 groupleadername     ,     
 groupleaderphone     ,    
 associationname       ,   
 associationleadername  ,  
 associationleaderphone  , 
 bankname ,
 tagnumber ,                
 longitude  ,               
 latitude    ,              
 picture      ,            
 barcode       ,           
 adminfullName  ,           
 adminphoneNumber,          
 centrename       ,         
 centrenumber      ,        
 dateCreated        ,       
 scanedbarcode       ,      
 updateStatus         ,     
 bagsofyield           ,    
 dateInsert      ) 
  select  Id ,     
 title  ,  
 farmerID, 
 surname  ,
 firstname ,                
 middlename ,               
 gender     ,               
 dob        ,               
 educationlevel,            
 phoneNumber ,              
 state      ,               
 LGA         ,              
 village      ,             
 farmersaddress,            
 height         ,           
 fatherssurname  ,          
 fathersfirstname ,         
 motherssurname    ,        
 mothersfirstname   ,       
 maritalstatus       ,      
 employmentstatus    ,      
 preferredlanguage   ,      
 surnamenextofkin    ,      
 firstnamenextofkin  ,      
 relationshipwithnextofkin, 
 townnextofkin            , 
 addressnextofkin          ,
 statenextofkin            ,
 lganextofkin              ,
 enumstate,
 enumlga   ,               
 enumvillage,              
 enumward    ,             
 farmerscrop  ,            
 farmsize      ,           
 farmlocation   ,          
 agricservices   ,         
 farmerslivestock ,        
 farmersfisheries  ,       
 groupname          ,      
 groupleadername     ,     
 groupleaderphone     ,    
 associationname       ,   
 associationleadername  ,  
 associationleaderphone  , 
 bankname ,
 tagnumber ,                
 longitude  ,               
 latitude    ,              
 picture      ,            
 barcode       ,           
 adminfullName  ,           
 adminphoneNumber,          
 centrename       ,         
 centrenumber      ,        
 dateCreated        ,       
 scanedbarcode       ,      
 updateStatus         ,     
 bagsofyield           ,    
 dateInsert        from farmersenrolII where enumstate = 'KOGI';