CREATE TABLE  G4_RESPONSE_TYPE 
   (	RES_TYPEID NUMBER NOT NULL ENABLE, 
  GES_YEAR number,
  vcid     number,
	RES_TYPENAME VARCHAR2(100) NOT NULL ENABLE, 
	LANGUAGEID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(100), 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	 CONSTRAINT G4_RESPONSE_TYP_PK PRIMARY KEY (RES_TYPEID)
  USING INDEX  ENABLE
   );
   
   
   
   CREATE TABLE  G4_RESPONSES 
   (	RESID NUMBER, 
	RESMSG VARCHAR2(500), 
  MSG_SEQ NUMBER(2,0), 
	RES_TYPEID NUMBER NOT NULL ENABLE, 
	LANGUAGEID NUMBER, 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	
	 CONSTRAINT G4_RESID_PK PRIMARY KEY (RESID)
  USING INDEX  ENABLE, 
	 CONSTRAINT G4_RESMSG_UK UNIQUE (RESMSG)
  USING INDEX  ENABLE
   );
   
   
CREATE OR REPLACE TRIGGER  G4_RESPONSES_TRIG 
BEFORE INSERT ON G4_responses
FOR EACH ROW
BEGIN
IF :new.resID is null
THEN SELECT G4_responses_seq.nextval
INTO :new.resID 
FROM DUAL;
END IF;
END;
 /  

CREATE OR REPLACE TRIGGER  G4_RESPONSE_TYPE_TRIG 
BEFORE INSERT ON G4_response_type
FOR EACH ROW
BEGIN
IF :new.res_typeID is null
THEN SELECT G4_response_type_seq.nextval
INTO :new.res_typeID
FROM DUAL;
END IF;
END;
   
   drop table G4_RESPONSE_TYPE;
   
   CREATE SEQUENCE   G4_RESPONSE_TYPE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 143 CACHE 20 ORDER  NOCYCLE
/

CREATE SEQUENCE   G4_RESPONSES_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14001 CACHE 2000 ORDER  NOCYCLE
/