CREATE TABLE  g4_INPUTS 
   (	INPUTID NUMBER NOT NULL ENABLE, 
	INPUTNAME VARCHAR2(200) NOT NULL ENABLE, 
	KEYWORD VARCHAR2(300) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(300) NOT NULL ENABLE, 
	SUBSIDYAMOUNT NUMBER NOT NULL DISABLE, 
	INPUTTYPEID NUMBER NOT NULL ENABLE, 
	INPUTCODE NUMBER NOT NULL DISABLE, 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	 CONSTRAINT g4_INPUTID_PK PRIMARY KEY (INPUTID)
  USING INDEX  ENABLE, 
	 CONSTRAINT g4_INPUTNAME_UK UNIQUE (INPUTNAME)
  USING INDEX  ENABLE, 
	 CONSTRAINT g4_KEYWORD_UK UNIQUE (KEYWORD)
  USING INDEX  ENABLE
   );
   
insert into  g4_inputs
select * from g4_inputs;

commit;

CREATE TABLE  g4_INPUTTYPES 
   (	INPUTTYPEID NUMBER NOT NULL ENABLE, 
	INPUTTYPENAME VARCHAR2(200) NOT NULL ENABLE, 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	 CONSTRAINT g4_INPUTTYPEID_PK PRIMARY KEY (INPUTTYPEID)
  USING INDEX  ENABLE, 
	 CONSTRAINT g4_INPUTTYPENAME_UK UNIQUE (INPUTTYPENAME)
  USING INDEX  ENABLE
   );
   
   insert into g4_INPUTTYPES
   select * from g4_inputtypes;
   
   
   CREATE SEQUENCE   g4_INPUTTYPES_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER  NOCYCLE;
   
   CREATE OR REPLACE TRIGGER  G4_INPUTTYPES_TRIG 
BEFORE INSERT ON G4_inputTypes
FOR EACH ROW
BEGIN
IF :new.inputTypeID is null
THEN SELECT G4_inputTypes_seq.nextval
INTO :new.inputTypeID
FROM DUAL;
END IF;
END;

select * from g4_inputs;

ALTER TABLE  G4_INPUTS ADD CONSTRAINT G4_INPUTS_INPUTTYPEID_FK FOREIGN KEY (INPUTTYPEID)
	  REFERENCES  G4_INPUTTYPES (INPUTTYPEID) ENABLE;
/

CREATE INDEX  IDX$$_0DAE0002G4 ON  G4_INPUTS (UPPER(KEYWORD));
/

CREATE INDEX  INPUT_KEYWORDG4 ON  G4_INPUTS (KEYWORD, INPUTNAME);
/

CREATE SEQUENCE   G4_INPUTS_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 ORDER  NOCYCLE;
/



CREATE OR REPLACE TRIGGER  G4_INPUTS_TRIG 
BEFORE INSERT ON G4_inputs
FOR EACH ROW
BEGIN
IF :new.inputid is null
THEN SELECT G4_inputs_seq.nextval
INTO :new.inputid
FROM DUAL;
END IF;
END;



select initcap(inputtypename)  n,inputtypeid i
from g3_inputtypes
order by 1
