ALTER TABLE  G4_ROUT_WARDS_MAPPING ADD CONSTRAINT G4_ROUTWM_STATEID_FK FOREIGN KEY (STATEID)
	  REFERENCES  G4_STATES (STATEID) ENABLE;
/
ALTER TABLE  G4_ROUT_WARDS_MAPPING ADD CONSTRAINT G4_ROUT_WARDS_MAPG_FK FOREIGN KEY (ROLLOUTID)
	  REFERENCES  G4_ROLLOUT (ROLLOUTID) ENABLE;
/
ALTER TABLE  G4_ROUT_WARDS_MAPPING ADD CONSTRAINT G4_ROUT_WARDS_MAP_FK FOREIGN KEY (BUNDLEID)
	  REFERENCES  G4_BUNDLES (BUNDLEID) ENABLE
/
ALTER TABLE  G4_ROUT_WARDS_MAPPING ADD CONSTRAINT G4_RWM_DEALERID_FK FOREIGN KEY (DEALERID)
	  REFERENCES  G4_AGRODEALERS (DEALERID) ENABLE
/
ALTER TABLE  G4_ROUT_WARDS_MAPPING ADD CONSTRAINT G4_RWM_FSTAFFID_FK FOREIGN KEY (FIELDSTAFFID)
	  REFERENCES  G4_FIELDSTAFF (FIELDSTAFFID) ENABLE
/
ALTER TABLE  G4_ROUT_WARDS_MAPPING ADD CONSTRAINT G4_RWM_WARDID_FK FOREIGN KEY (WARDID)
	  REFERENCES  G4_WARDS (WARDID) ENABLE
/