CREATE TABLE  G4_VALUE_CHAIN 
   (	VCID NUMBER, 
	VCNAME VARCHAR2(50), 
	INSERTEDBY NUMBER, 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	VKEYWORD VARCHAR2(20), 
	 CONSTRAINT G4_VALUE_CHAIN_VCID_PK PRIMARY KEY (VCID)
  USING INDEX  ENABLE, 
	 CONSTRAINT G4_VALUE_CHAIN_VCNAME_UK UNIQUE (VCNAME)
  USING INDEX  ENABLE
   );
   
   drop sequence G4_VALUE_CHAIN_SEQ ;
   
   CREATE SEQUENCE   G4_VALUE_CHAIN_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 146 CACHE 20 ORDER  NOCYCLE