 insert into kogitest(Id ,     
 title  ,  
 farmerID, 
 surname  ,
 firstname ,                
 middlename ,               
 gender     ,               
 dob        ,               
 educationlevel,            
 phoneNumber ,              
 state      ,               
 LGA         ,              
 village      ,             
 farmersaddress,            
 height         ,           
 fatherssurname  ,          
 fathersfirstname ,         
 motherssurname    ,        
 mothersfirstname   ,       
 maritalstatus       ,      
 employmentstatus    ,      
 preferredlanguage   ,      
 surnamenextofkin    ,      
 firstnamenextofkin  ,      
 relationshipwithnextofkin, 
 townnextofkin            , 
 addressnextofkin          ,
 statenextofkin            ,
 lganextofkin              ,
 enumstate,
 enumlga   ,               
 enumvillage,              
 enumward    ,             
 farmerscrop  ,            
 farmsize      ,           
 farmlocation   ,          
 agricservices   ,         
 farmerslivestock ,        
 farmersfisheries  ,       
 groupname          ,      
 groupleadername     ,     
 groupleaderphone     ,    
 associationname       ,   
 associationleadername  ,  
 associationleaderphone  , 
 bankname ,
 tagnumber ,                
 longitude  ,               
 latitude    ,              
 picture      ,            
 barcode       ,           
 adminfullName  ,           
 adminphoneNumber,          
 centrename       ,         
 centrenumber      ,        
 dateCreated        ,       
 scanedbarcode       ,      
 updateStatus         ,     
 bagsofyield           ,    
 dateInsert ,
 status      ) 
  select  Id ,     
 title  ,  
 farmerID, 
 surname  ,
 firstname ,                
 middlename ,               
 gender     ,               
 dob        ,               
 educationlevel,            
 phoneNumber ,              
 state      ,               
 LGA         ,              
 village      ,             
 farmersaddress,            
 height         ,           
 fatherssurname  ,          
 fathersfirstname ,         
 motherssurname    ,        
 mothersfirstname   ,       
 maritalstatus       ,      
 employmentstatus    ,      
 preferredlanguage   ,      
 surnamenextofkin    ,      
 firstnamenextofkin  ,      
 relationshipwithnextofkin, 
 townnextofkin            , 
 addressnextofkin          ,
 statenextofkin            ,
 lganextofkin              ,
 enumstate,
 enumlga   ,               
 enumvillage,              
 enumward    ,             
 farmerscrop  ,            
 farmsize      ,           
 farmlocation   ,          
 agricservices   ,         
 farmerslivestock ,        
 farmersfisheries  ,       
 groupname          ,      
 groupleadername     ,     
 groupleaderphone     ,    
 associationname       ,   
 associationleadername  ,  
 associationleaderphone  , 
 bankname ,
 tagnumber ,                
 longitude  ,               
 latitude    ,              
 picture      ,            
 barcode       ,           
 adminfullName  ,           
 adminphoneNumber,          
 centrename       ,         
 centrenumber      ,        
 dateCreated        ,       
 scanedbarcode       ,      
 updateStatus         ,     
 bagsofyield           ,    
 dateInsert ,
 status        from farmersenrolII where enumstate = 'AKWA IBOM';
 
 
 DELETE FROM kogitest  
WHERE kogitestid IN (SELECT * 
             FROM (SELECT farmerID FROM kogitest 
                   GROUP BY farmerID HAVING (COUNT(*) > 1)
                  ) AS A
            );
            
         select k.farmerID,count(k.farmerID) tt from kogitest k,farmersenrol f 
         where k.farmerID = f.farmerID group by k.farmerID order by 2 desc ;   
            
            
Delete from kogitest 
WHERE kogitestid NOT IN (SELECT * 
FROM (SELECT MIN(n.kogitestid) FROM kogitest n 
GROUP BY n.farmerid) x);



dd if=/dev/sda8 of=/dev/sdc1 conv=noerror bs=1M