SELECT 
   G4_ROLLOUT.ROLLOUTID ROLLOUTID, 
   G4_ROLLOUT.ROLLOUTNAME ROLLOUTNAME, 
   G4_ROLLOUT.REDEMP_CENTER REDEMP_CENTER, 
   G4_ROLLOUT.ROLLOUTDATE ROLLOUTDATE, 
   G4_BUNDLES.BUNDLENAME BUNDLENAME,
   G4_ROLLOUT.FARMERS_CON FARMERS_CON,
   G4_VALUE_CHAIN.VCNAME VCNAME, 
   G4_STATES.STATENAME STATENAME, 
   G4_LGA.LGANAME LGANAME,
   G4_RESPONSE_TYPE.RES_TYPENAME RES_TYPENAME,
    G4_ROLLOUT.ROLLOUTSTATUS ROLLOUTSTATUS, 
      G4_AGRODEALERS.DEALERNAME DEALERNAME, 
   G4_FIELDSTAFF.FIELDSTAFFNAME FIELDSTAFFNAME
FROM  G4_ROLLOUT,G4_LGA,G4_STATES,G4_BUNDLES,G4_VALUE_CHAIN,G4_FIELDSTAFF,G4_DEALERS,G4_response_type
WHERE G4_ROLLOUT.LGAID     =  G4_LGA.LGAID
AND   G4_ROLLOUT.STATEID   =  G4_STATES.STATEID
AND   G4_ROLLOUT.BUNDLEID  =  G4_BUNDLES.BUNDLEID
AND   G4_ROLLOUT.DEALERID  =  G4_AGRODEALERS.DEALERID
AND   G4_ROLLOUT.VCID      =  G4_VALUE_CHAIN.VCID
AND   G4_ROLLOUT.FIELDSTAFFID      =  G4_FIELDSTAFF.FIELDSTAFFID
AND   G4_ROLLOUT.RES_TYPEID =  G4_response_type.RES_TYPEID;