CREATE TABLE  G4_FIELDSTAFF 
   (	FIELDSTAFFID NUMBER NOT NULL ENABLE, 
	FIELDSTAFFNAME VARCHAR2(50) NOT NULL ENABLE, 
	STATEID NUMBER NOT NULL ENABLE, 
	LGAID NUMBER NOT NULL ENABLE, 
	AGRODEALERID NUMBER NOT NULL ENABLE, 
	DATECREATED TIMESTAMP (6) DEFAULT systimestamp, 
	DATEMODIFIED TIMESTAMP (6) DEFAULT systimestamp, 
	PHONENUMBER NUMBER, 
	 CONSTRAINT G4_FIELDSTAFFID_PK PRIMARY KEY (FIELDSTAFFID)
  USING INDEX  ENABLE, 
	 CONSTRAINT G4_FIELDSTAFFNAME_UK UNIQUE (FIELDSTAFFNAME)
  USING INDEX  ENABLE, 
	 CONSTRAINT G4MSISDN_UNIQUE_PHONE UNIQUE (PHONENUMBER)
  USING INDEX  ENABLE
   )
/

mysql -u Napi -pNap1Farmer


CREATE SEQUENCE   G4_FIELDSTAFF_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3432 CACHE 20 ORDER  NOCYCLE
/
